name: pynance
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.21.6
  - pandas=1.4.4
  - matplotlib=3.5.3
  - scikit-learn=1.6.1
  - yfinance=0.2.26
  - pip
  - pip:
      - black==25.1.0
